// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v3.21.12
// source: v1/pagebroker.proto

package pagebroker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Failure_Code int32

const (
	// No failure code was supplied.
	Failure_UNSPECIFIED Failure_Code = 0
	// The request is malformed or unsupported. PageBroker did not mutate transaction state.
	Failure_INVALID_REQUEST Failure_Code = 1
	// The transaction is unknown or has reached the opposite terminal state.
	Failure_TRANSACTION_NOT_FOUND Failure_Code = 2
	// The transaction ID or checkpoint destination conflicts with an existing transaction or output.
	Failure_TRANSACTION_CONFLICT Failure_Code = 3
	// Tmpfs staging lacks space. PageBroker did not create staging for this request.
	Failure_INSUFFICIENT_STORAGE Failure_Code = 4
	// Storage I/O failed. The caller may Abort the transaction before retrying with a new transaction ID.
	Failure_STORAGE_ERROR Failure_Code = 5
	// An unexpected broker failure occurred. The caller may Abort the transaction before retrying.
	Failure_INTERNAL_ERROR Failure_Code = 6
)

// Enum value maps for Failure_Code.
var (
	Failure_Code_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "INVALID_REQUEST",
		2: "TRANSACTION_NOT_FOUND",
		3: "TRANSACTION_CONFLICT",
		4: "INSUFFICIENT_STORAGE",
		5: "STORAGE_ERROR",
		6: "INTERNAL_ERROR",
	}
	Failure_Code_value = map[string]int32{
		"UNSPECIFIED":           0,
		"INVALID_REQUEST":       1,
		"TRANSACTION_NOT_FOUND": 2,
		"TRANSACTION_CONFLICT":  3,
		"INSUFFICIENT_STORAGE":  4,
		"STORAGE_ERROR":         5,
		"INTERNAL_ERROR":        6,
	}
)

func (x Failure_Code) Enum() *Failure_Code {
	p := new(Failure_Code)
	*p = x
	return p
}

func (x Failure_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Failure_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_pagebroker_proto_enumTypes[0].Descriptor()
}

func (Failure_Code) Type() protoreflect.EnumType {
	return &file_v1_pagebroker_proto_enumTypes[0]
}

func (x Failure_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Failure_Code.Descriptor instead.
func (Failure_Code) EnumDescriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{15, 0}
}

type FilesystemStorage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directory     *string                `protobuf:"bytes,1,opt,name=directory,proto3,oneof" json:"directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemStorage) Reset() {
	*x = FilesystemStorage{}
	mi := &file_v1_pagebroker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemStorage) ProtoMessage() {}

func (x *FilesystemStorage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemStorage.ProtoReflect.Descriptor instead.
func (*FilesystemStorage) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{0}
}

func (x *FilesystemStorage) GetDirectory() string {
	if x != nil && x.Directory != nil {
		return *x.Directory
	}
	return ""
}

type StorageBackend struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requests require exactly one storage kind.
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*StorageBackend_Filesystem
	Kind          isStorageBackend_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageBackend) Reset() {
	*x = StorageBackend{}
	mi := &file_v1_pagebroker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageBackend) ProtoMessage() {}

func (x *StorageBackend) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageBackend.ProtoReflect.Descriptor instead.
func (*StorageBackend) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{1}
}

func (x *StorageBackend) GetKind() isStorageBackend_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *StorageBackend) GetFilesystem() *FilesystemStorage {
	if x != nil {
		if x, ok := x.Kind.(*StorageBackend_Filesystem); ok {
			return x.Filesystem
		}
	}
	return nil
}

type isStorageBackend_Kind interface {
	isStorageBackend_Kind()
}

type StorageBackend_Filesystem struct {
	Filesystem *FilesystemStorage `protobuf:"bytes,1,opt,name=filesystem,proto3,oneof"`
}

func (*StorageBackend_Filesystem) isStorageBackend_Kind() {}

type PosixCopyIOEngine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PosixCopyIOEngine) Reset() {
	*x = PosixCopyIOEngine{}
	mi := &file_v1_pagebroker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PosixCopyIOEngine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosixCopyIOEngine) ProtoMessage() {}

func (x *PosixCopyIOEngine) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosixCopyIOEngine.ProtoReflect.Descriptor instead.
func (*PosixCopyIOEngine) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{2}
}

type IOEngine struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requests require exactly one I/O engine.
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*IOEngine_PosixCopy
	Kind          isIOEngine_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IOEngine) Reset() {
	*x = IOEngine{}
	mi := &file_v1_pagebroker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IOEngine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOEngine) ProtoMessage() {}

func (x *IOEngine) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOEngine.ProtoReflect.Descriptor instead.
func (*IOEngine) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{3}
}

func (x *IOEngine) GetKind() isIOEngine_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *IOEngine) GetPosixCopy() *PosixCopyIOEngine {
	if x != nil {
		if x, ok := x.Kind.(*IOEngine_PosixCopy); ok {
			return x.PosixCopy
		}
	}
	return nil
}

type isIOEngine_Kind interface {
	isIOEngine_Kind()
}

type IOEngine_PosixCopy struct {
	PosixCopy *PosixCopyIOEngine `protobuf:"bytes,1,opt,name=posix_copy,json=posixCopy,proto3,oneof"`
}

func (*IOEngine_PosixCopy) isIOEngine_Kind() {}

type StagedRestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *StorageBackend        `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	IoEngine      *IOEngine              `protobuf:"bytes,2,opt,name=io_engine,json=ioEngine,proto3" json:"io_engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StagedRestoreRequest) Reset() {
	*x = StagedRestoreRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StagedRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StagedRestoreRequest) ProtoMessage() {}

func (x *StagedRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StagedRestoreRequest.ProtoReflect.Descriptor instead.
func (*StagedRestoreRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{4}
}

func (x *StagedRestoreRequest) GetSource() *StorageBackend {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *StagedRestoreRequest) GetIoEngine() *IOEngine {
	if x != nil {
		return x.IoEngine
	}
	return nil
}

// Allows a future GPU engine to read source data without a staging directory.
type DirectRestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *StorageBackend        `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	IoEngine      *IOEngine              `protobuf:"bytes,2,opt,name=io_engine,json=ioEngine,proto3" json:"io_engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectRestoreRequest) Reset() {
	*x = DirectRestoreRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectRestoreRequest) ProtoMessage() {}

func (x *DirectRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectRestoreRequest.ProtoReflect.Descriptor instead.
func (*DirectRestoreRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{5}
}

func (x *DirectRestoreRequest) GetSource() *StorageBackend {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *DirectRestoreRequest) GetIoEngine() *IOEngine {
	if x != nil {
		return x.IoEngine
	}
	return nil
}

type PrepareStagedCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   *StorageBackend        `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	IoEngine      *IOEngine              `protobuf:"bytes,2,opt,name=io_engine,json=ioEngine,proto3" json:"io_engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareStagedCheckpointRequest) Reset() {
	*x = PrepareStagedCheckpointRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareStagedCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareStagedCheckpointRequest) ProtoMessage() {}

func (x *PrepareStagedCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareStagedCheckpointRequest.ProtoReflect.Descriptor instead.
func (*PrepareStagedCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{6}
}

func (x *PrepareStagedCheckpointRequest) GetDestination() *StorageBackend {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *PrepareStagedCheckpointRequest) GetIoEngine() *IOEngine {
	if x != nil {
		return x.IoEngine
	}
	return nil
}

// Completes a live transaction. PageBroker retains up to 1,024 terminal transactions for up to one hour.
// Repeating Commit for a retained committed transaction returns CommitComplete; Commit for an aborted, expired, or
// unknown transaction returns TRANSACTION_NOT_FOUND.
type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{7}
}

// Releases PageBroker state for a live transaction. PageBroker retains up to 1,024 terminal transactions for up to
// one hour. Repeating Abort for a retained aborted transaction returns AbortComplete; Abort for a committed, expired,
// or unknown transaction returns TRANSACTION_NOT_FOUND.
type AbortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequest) Reset() {
	*x = AbortRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequest) ProtoMessage() {}

func (x *AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequest.ProtoReflect.Descriptor instead.
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{8}
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Snapshot assigns an ID to each request.
	RequestId *string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	// Snapshot assigns a unique transaction ID before the first request and does not reuse it while PageBroker retains it.
	// An uncommitted transaction expires one hour after staging begins.
	TransactionId *string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3,oneof" json:"transaction_id,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*Request_StagedRestore
	//	*Request_PrepareStagedCheckpoint
	//	*Request_Commit
	//	*Request_Abort
	//	*Request_DirectRestore
	Command       isRequest_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_v1_pagebroker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{9}
}

func (x *Request) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

func (x *Request) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

func (x *Request) GetCommand() isRequest_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Request) GetStagedRestore() *StagedRestoreRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_StagedRestore); ok {
			return x.StagedRestore
		}
	}
	return nil
}

func (x *Request) GetPrepareStagedCheckpoint() *PrepareStagedCheckpointRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_PrepareStagedCheckpoint); ok {
			return x.PrepareStagedCheckpoint
		}
	}
	return nil
}

func (x *Request) GetCommit() *CommitRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

func (x *Request) GetAbort() *AbortRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_Abort); ok {
			return x.Abort
		}
	}
	return nil
}

func (x *Request) GetDirectRestore() *DirectRestoreRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_DirectRestore); ok {
			return x.DirectRestore
		}
	}
	return nil
}

type isRequest_Command interface {
	isRequest_Command()
}

type Request_StagedRestore struct {
	StagedRestore *StagedRestoreRequest `protobuf:"bytes,3,opt,name=staged_restore,json=stagedRestore,proto3,oneof"`
}

type Request_PrepareStagedCheckpoint struct {
	PrepareStagedCheckpoint *PrepareStagedCheckpointRequest `protobuf:"bytes,4,opt,name=prepare_staged_checkpoint,json=prepareStagedCheckpoint,proto3,oneof"`
}

type Request_Commit struct {
	Commit *CommitRequest `protobuf:"bytes,5,opt,name=commit,proto3,oneof"`
}

type Request_Abort struct {
	Abort *AbortRequest `protobuf:"bytes,6,opt,name=abort,proto3,oneof"`
}

type Request_DirectRestore struct {
	DirectRestore *DirectRestoreRequest `protobuf:"bytes,7,opt,name=direct_restore,json=directRestore,proto3,oneof"`
}

func (*Request_StagedRestore) isRequest_Command() {}

func (*Request_PrepareStagedCheckpoint) isRequest_Command() {}

func (*Request_Commit) isRequest_Command() {}

func (*Request_Abort) isRequest_Command() {}

func (*Request_DirectRestore) isRequest_Command() {}

type StagedRestoreDirectory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImageDirectory *string                `protobuf:"bytes,1,opt,name=image_directory,json=imageDirectory,proto3,oneof" json:"image_directory,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StagedRestoreDirectory) Reset() {
	*x = StagedRestoreDirectory{}
	mi := &file_v1_pagebroker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StagedRestoreDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StagedRestoreDirectory) ProtoMessage() {}

func (x *StagedRestoreDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StagedRestoreDirectory.ProtoReflect.Descriptor instead.
func (*StagedRestoreDirectory) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{10}
}

func (x *StagedRestoreDirectory) GetImageDirectory() string {
	if x != nil && x.ImageDirectory != nil {
		return *x.ImageDirectory
	}
	return ""
}

type DirectRestoreReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectRestoreReady) Reset() {
	*x = DirectRestoreReady{}
	mi := &file_v1_pagebroker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectRestoreReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectRestoreReady) ProtoMessage() {}

func (x *DirectRestoreReady) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectRestoreReady.ProtoReflect.Descriptor instead.
func (*DirectRestoreReady) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{11}
}

type StagedCheckpointDirectory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImageDirectory *string                `protobuf:"bytes,1,opt,name=image_directory,json=imageDirectory,proto3,oneof" json:"image_directory,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StagedCheckpointDirectory) Reset() {
	*x = StagedCheckpointDirectory{}
	mi := &file_v1_pagebroker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StagedCheckpointDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StagedCheckpointDirectory) ProtoMessage() {}

func (x *StagedCheckpointDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StagedCheckpointDirectory.ProtoReflect.Descriptor instead.
func (*StagedCheckpointDirectory) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{12}
}

func (x *StagedCheckpointDirectory) GetImageDirectory() string {
	if x != nil && x.ImageDirectory != nil {
		return *x.ImageDirectory
	}
	return ""
}

type CommitComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitComplete) Reset() {
	*x = CommitComplete{}
	mi := &file_v1_pagebroker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitComplete) ProtoMessage() {}

func (x *CommitComplete) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitComplete.ProtoReflect.Descriptor instead.
func (*CommitComplete) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{13}
}

// Confirms only that PageBroker transaction state/content was released; it says nothing about the target
// process or CUDA state.
type AbortComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortComplete) Reset() {
	*x = AbortComplete{}
	mi := &file_v1_pagebroker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortComplete) ProtoMessage() {}

func (x *AbortComplete) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortComplete.ProtoReflect.Descriptor instead.
func (*AbortComplete) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{14}
}

type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *Failure_Code          `protobuf:"varint,1,opt,name=code,proto3,enum=snapshot.pagebroker.v1.Failure_Code,oneof" json:"code,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_v1_pagebroker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{15}
}

func (x *Failure) GetCode() Failure_Code {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return Failure_UNSPECIFIED
}

func (x *Failure) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     *string                `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	TransactionId *string                `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3,oneof" json:"transaction_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*Response_StagedRestoreDirectory
	//	*Response_StagedCheckpointDirectory
	//	*Response_CommitComplete
	//	*Response_AbortComplete
	//	*Response_Failure
	//	*Response_DirectRestoreReady
	Result        isResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_v1_pagebroker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{16}
}

func (x *Response) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

func (x *Response) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

func (x *Response) GetResult() isResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Response) GetStagedRestoreDirectory() *StagedRestoreDirectory {
	if x != nil {
		if x, ok := x.Result.(*Response_StagedRestoreDirectory); ok {
			return x.StagedRestoreDirectory
		}
	}
	return nil
}

func (x *Response) GetStagedCheckpointDirectory() *StagedCheckpointDirectory {
	if x != nil {
		if x, ok := x.Result.(*Response_StagedCheckpointDirectory); ok {
			return x.StagedCheckpointDirectory
		}
	}
	return nil
}

func (x *Response) GetCommitComplete() *CommitComplete {
	if x != nil {
		if x, ok := x.Result.(*Response_CommitComplete); ok {
			return x.CommitComplete
		}
	}
	return nil
}

func (x *Response) GetAbortComplete() *AbortComplete {
	if x != nil {
		if x, ok := x.Result.(*Response_AbortComplete); ok {
			return x.AbortComplete
		}
	}
	return nil
}

func (x *Response) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Result.(*Response_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

func (x *Response) GetDirectRestoreReady() *DirectRestoreReady {
	if x != nil {
		if x, ok := x.Result.(*Response_DirectRestoreReady); ok {
			return x.DirectRestoreReady
		}
	}
	return nil
}

type isResponse_Result interface {
	isResponse_Result()
}

type Response_StagedRestoreDirectory struct {
	StagedRestoreDirectory *StagedRestoreDirectory `protobuf:"bytes,3,opt,name=staged_restore_directory,json=stagedRestoreDirectory,proto3,oneof"`
}

type Response_StagedCheckpointDirectory struct {
	StagedCheckpointDirectory *StagedCheckpointDirectory `protobuf:"bytes,4,opt,name=staged_checkpoint_directory,json=stagedCheckpointDirectory,proto3,oneof"`
}

type Response_CommitComplete struct {
	CommitComplete *CommitComplete `protobuf:"bytes,5,opt,name=commit_complete,json=commitComplete,proto3,oneof"`
}

type Response_AbortComplete struct {
	AbortComplete *AbortComplete `protobuf:"bytes,6,opt,name=abort_complete,json=abortComplete,proto3,oneof"`
}

type Response_Failure struct {
	Failure *Failure `protobuf:"bytes,7,opt,name=failure,proto3,oneof"`
}

type Response_DirectRestoreReady struct {
	DirectRestoreReady *DirectRestoreReady `protobuf:"bytes,8,opt,name=direct_restore_ready,json=directRestoreReady,proto3,oneof"`
}

func (*Response_StagedRestoreDirectory) isResponse_Result() {}

func (*Response_StagedCheckpointDirectory) isResponse_Result() {}

func (*Response_CommitComplete) isResponse_Result() {}

func (*Response_AbortComplete) isResponse_Result() {}

func (*Response_Failure) isResponse_Result() {}

func (*Response_DirectRestoreReady) isResponse_Result() {}

var File_v1_pagebroker_proto protoreflect.FileDescriptor

const file_v1_pagebroker_proto_rawDesc = "" +
	"\n" +
	"\x13v1/pagebroker.proto\x12\x16snapshot.pagebroker.v1\"D\n" +
	"\x11FilesystemStorage\x12!\n" +
	"\tdirectory\x18\x01 \x01(\tH\x00R\tdirectory\x88\x01\x01B\f\n" +
	"\n" +
	"_directory\"e\n" +
	"\x0eStorageBackend\x12K\n" +
	"\n" +
	"filesystem\x18\x01 \x01(\v2).snapshot.pagebroker.v1.FilesystemStorageH\x00R\n" +
	"filesystemB\x06\n" +
	"\x04kind\"\x13\n" +
	"\x11PosixCopyIOEngine\"^\n" +
	"\bIOEngine\x12J\n" +
	"\n" +
	"posix_copy\x18\x01 \x01(\v2).snapshot.pagebroker.v1.PosixCopyIOEngineH\x00R\tposixCopyB\x06\n" +
	"\x04kind\"\x95\x01\n" +
	"\x14StagedRestoreRequest\x12>\n" +
	"\x06source\x18\x01 \x01(\v2&.snapshot.pagebroker.v1.StorageBackendR\x06source\x12=\n" +
	"\tio_engine\x18\x02 \x01(\v2 .snapshot.pagebroker.v1.IOEngineR\bioEngine\"\x95\x01\n" +
	"\x14DirectRestoreRequest\x12>\n" +
	"\x06source\x18\x01 \x01(\v2&.snapshot.pagebroker.v1.StorageBackendR\x06source\x12=\n" +
	"\tio_engine\x18\x02 \x01(\v2 .snapshot.pagebroker.v1.IOEngineR\bioEngine\"\xa9\x01\n" +
	"\x1ePrepareStagedCheckpointRequest\x12H\n" +
	"\vdestination\x18\x01 \x01(\v2&.snapshot.pagebroker.v1.StorageBackendR\vdestination\x12=\n" +
	"\tio_engine\x18\x02 \x01(\v2 .snapshot.pagebroker.v1.IOEngineR\bioEngine\"\x0f\n" +
	"\rCommitRequest\"\x0e\n" +
	"\fAbortRequest\"\xa9\x04\n" +
	"\aRequest\x12\"\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tH\x01R\trequestId\x88\x01\x01\x12*\n" +
	"\x0etransaction_id\x18\x02 \x01(\tH\x02R\rtransactionId\x88\x01\x01\x12U\n" +
	"\x0estaged_restore\x18\x03 \x01(\v2,.snapshot.pagebroker.v1.StagedRestoreRequestH\x00R\rstagedRestore\x12t\n" +
	"\x19prepare_staged_checkpoint\x18\x04 \x01(\v26.snapshot.pagebroker.v1.PrepareStagedCheckpointRequestH\x00R\x17prepareStagedCheckpoint\x12?\n" +
	"\x06commit\x18\x05 \x01(\v2%.snapshot.pagebroker.v1.CommitRequestH\x00R\x06commit\x12<\n" +
	"\x05abort\x18\x06 \x01(\v2$.snapshot.pagebroker.v1.AbortRequestH\x00R\x05abort\x12U\n" +
	"\x0edirect_restore\x18\a \x01(\v2,.snapshot.pagebroker.v1.DirectRestoreRequestH\x00R\rdirectRestoreB\t\n" +
	"\acommandB\r\n" +
	"\v_request_idB\x11\n" +
	"\x0f_transaction_id\"Z\n" +
	"\x16StagedRestoreDirectory\x12,\n" +
	"\x0fimage_directory\x18\x01 \x01(\tH\x00R\x0eimageDirectory\x88\x01\x01B\x12\n" +
	"\x10_image_directory\"\x14\n" +
	"\x12DirectRestoreReady\"]\n" +
	"\x19StagedCheckpointDirectory\x12,\n" +
	"\x0fimage_directory\x18\x01 \x01(\tH\x00R\x0eimageDirectory\x88\x01\x01B\x12\n" +
	"\x10_image_directory\"\x10\n" +
	"\x0eCommitComplete\"\x0f\n" +
	"\rAbortComplete\"\xa1\x02\n" +
	"\aFailure\x12=\n" +
	"\x04code\x18\x01 \x01(\x0e2$.snapshot.pagebroker.v1.Failure.CodeH\x00R\x04code\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x01R\amessage\x88\x01\x01\"\xa2\x01\n" +
	"\x04Code\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fINVALID_REQUEST\x10\x01\x12\x19\n" +
	"\x15TRANSACTION_NOT_FOUND\x10\x02\x12\x18\n" +
	"\x14TRANSACTION_CONFLICT\x10\x03\x12\x18\n" +
	"\x14INSUFFICIENT_STORAGE\x10\x04\x12\x11\n" +
	"\rSTORAGE_ERROR\x10\x05\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x06B\a\n" +
	"\x05_codeB\n" +
	"\n" +
	"\b_message\"\xa7\x05\n" +
	"\bResponse\x12\"\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tH\x01R\trequestId\x88\x01\x01\x12*\n" +
	"\x0etransaction_id\x18\x02 \x01(\tH\x02R\rtransactionId\x88\x01\x01\x12j\n" +
	"\x18staged_restore_directory\x18\x03 \x01(\v2..snapshot.pagebroker.v1.StagedRestoreDirectoryH\x00R\x16stagedRestoreDirectory\x12s\n" +
	"\x1bstaged_checkpoint_directory\x18\x04 \x01(\v21.snapshot.pagebroker.v1.StagedCheckpointDirectoryH\x00R\x19stagedCheckpointDirectory\x12Q\n" +
	"\x0fcommit_complete\x18\x05 \x01(\v2&.snapshot.pagebroker.v1.CommitCompleteH\x00R\x0ecommitComplete\x12N\n" +
	"\x0eabort_complete\x18\x06 \x01(\v2%.snapshot.pagebroker.v1.AbortCompleteH\x00R\rabortComplete\x12;\n" +
	"\afailure\x18\a \x01(\v2\x1f.snapshot.pagebroker.v1.FailureH\x00R\afailure\x12^\n" +
	"\x14direct_restore_ready\x18\b \x01(\v2*.snapshot.pagebroker.v1.DirectRestoreReadyH\x00R\x12directRestoreReadyB\b\n" +
	"\x06resultB\r\n" +
	"\v_request_idB\x11\n" +
	"\x0f_transaction_idB9Z7github.com/ai-dynamo/snapshot/agent/internal/pagebrokerb\x06proto3"

var (
	file_v1_pagebroker_proto_rawDescOnce sync.Once
	file_v1_pagebroker_proto_rawDescData []byte
)

func file_v1_pagebroker_proto_rawDescGZIP() []byte {
	file_v1_pagebroker_proto_rawDescOnce.Do(func() {
		file_v1_pagebroker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_pagebroker_proto_rawDesc), len(file_v1_pagebroker_proto_rawDesc)))
	})
	return file_v1_pagebroker_proto_rawDescData
}

var file_v1_pagebroker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_pagebroker_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_v1_pagebroker_proto_goTypes = []any{
	(Failure_Code)(0),                      // 0: snapshot.pagebroker.v1.Failure.Code
	(*FilesystemStorage)(nil),              // 1: snapshot.pagebroker.v1.FilesystemStorage
	(*StorageBackend)(nil),                 // 2: snapshot.pagebroker.v1.StorageBackend
	(*PosixCopyIOEngine)(nil),              // 3: snapshot.pagebroker.v1.PosixCopyIOEngine
	(*IOEngine)(nil),                       // 4: snapshot.pagebroker.v1.IOEngine
	(*StagedRestoreRequest)(nil),           // 5: snapshot.pagebroker.v1.StagedRestoreRequest
	(*DirectRestoreRequest)(nil),           // 6: snapshot.pagebroker.v1.DirectRestoreRequest
	(*PrepareStagedCheckpointRequest)(nil), // 7: snapshot.pagebroker.v1.PrepareStagedCheckpointRequest
	(*CommitRequest)(nil),                  // 8: snapshot.pagebroker.v1.CommitRequest
	(*AbortRequest)(nil),                   // 9: snapshot.pagebroker.v1.AbortRequest
	(*Request)(nil),                        // 10: snapshot.pagebroker.v1.Request
	(*StagedRestoreDirectory)(nil),         // 11: snapshot.pagebroker.v1.StagedRestoreDirectory
	(*DirectRestoreReady)(nil),             // 12: snapshot.pagebroker.v1.DirectRestoreReady
	(*StagedCheckpointDirectory)(nil),      // 13: snapshot.pagebroker.v1.StagedCheckpointDirectory
	(*CommitComplete)(nil),                 // 14: snapshot.pagebroker.v1.CommitComplete
	(*AbortComplete)(nil),                  // 15: snapshot.pagebroker.v1.AbortComplete
	(*Failure)(nil),                        // 16: snapshot.pagebroker.v1.Failure
	(*Response)(nil),                       // 17: snapshot.pagebroker.v1.Response
}
var file_v1_pagebroker_proto_depIdxs = []int32{
	1,  // 0: snapshot.pagebroker.v1.StorageBackend.filesystem:type_name -> snapshot.pagebroker.v1.FilesystemStorage
	3,  // 1: snapshot.pagebroker.v1.IOEngine.posix_copy:type_name -> snapshot.pagebroker.v1.PosixCopyIOEngine
	2,  // 2: snapshot.pagebroker.v1.StagedRestoreRequest.source:type_name -> snapshot.pagebroker.v1.StorageBackend
	4,  // 3: snapshot.pagebroker.v1.StagedRestoreRequest.io_engine:type_name -> snapshot.pagebroker.v1.IOEngine
	2,  // 4: snapshot.pagebroker.v1.DirectRestoreRequest.source:type_name -> snapshot.pagebroker.v1.StorageBackend
	4,  // 5: snapshot.pagebroker.v1.DirectRestoreRequest.io_engine:type_name -> snapshot.pagebroker.v1.IOEngine
	2,  // 6: snapshot.pagebroker.v1.PrepareStagedCheckpointRequest.destination:type_name -> snapshot.pagebroker.v1.StorageBackend
	4,  // 7: snapshot.pagebroker.v1.PrepareStagedCheckpointRequest.io_engine:type_name -> snapshot.pagebroker.v1.IOEngine
	5,  // 8: snapshot.pagebroker.v1.Request.staged_restore:type_name -> snapshot.pagebroker.v1.StagedRestoreRequest
	7,  // 9: snapshot.pagebroker.v1.Request.prepare_staged_checkpoint:type_name -> snapshot.pagebroker.v1.PrepareStagedCheckpointRequest
	8,  // 10: snapshot.pagebroker.v1.Request.commit:type_name -> snapshot.pagebroker.v1.CommitRequest
	9,  // 11: snapshot.pagebroker.v1.Request.abort:type_name -> snapshot.pagebroker.v1.AbortRequest
	6,  // 12: snapshot.pagebroker.v1.Request.direct_restore:type_name -> snapshot.pagebroker.v1.DirectRestoreRequest
	0,  // 13: snapshot.pagebroker.v1.Failure.code:type_name -> snapshot.pagebroker.v1.Failure.Code
	11, // 14: snapshot.pagebroker.v1.Response.staged_restore_directory:type_name -> snapshot.pagebroker.v1.StagedRestoreDirectory
	13, // 15: snapshot.pagebroker.v1.Response.staged_checkpoint_directory:type_name -> snapshot.pagebroker.v1.StagedCheckpointDirectory
	14, // 16: snapshot.pagebroker.v1.Response.commit_complete:type_name -> snapshot.pagebroker.v1.CommitComplete
	15, // 17: snapshot.pagebroker.v1.Response.abort_complete:type_name -> snapshot.pagebroker.v1.AbortComplete
	16, // 18: snapshot.pagebroker.v1.Response.failure:type_name -> snapshot.pagebroker.v1.Failure
	12, // 19: snapshot.pagebroker.v1.Response.direct_restore_ready:type_name -> snapshot.pagebroker.v1.DirectRestoreReady
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_v1_pagebroker_proto_init() }
func file_v1_pagebroker_proto_init() {
	if File_v1_pagebroker_proto != nil {
		return
	}
	file_v1_pagebroker_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_pagebroker_proto_msgTypes[1].OneofWrappers = []any{
		(*StorageBackend_Filesystem)(nil),
	}
	file_v1_pagebroker_proto_msgTypes[3].OneofWrappers = []any{
		(*IOEngine_PosixCopy)(nil),
	}
	file_v1_pagebroker_proto_msgTypes[9].OneofWrappers = []any{
		(*Request_StagedRestore)(nil),
		(*Request_PrepareStagedCheckpoint)(nil),
		(*Request_Commit)(nil),
		(*Request_Abort)(nil),
		(*Request_DirectRestore)(nil),
	}
	file_v1_pagebroker_proto_msgTypes[10].OneofWrappers = []any{}
	file_v1_pagebroker_proto_msgTypes[12].OneofWrappers = []any{}
	file_v1_pagebroker_proto_msgTypes[15].OneofWrappers = []any{}
	file_v1_pagebroker_proto_msgTypes[16].OneofWrappers = []any{
		(*Response_StagedRestoreDirectory)(nil),
		(*Response_StagedCheckpointDirectory)(nil),
		(*Response_CommitComplete)(nil),
		(*Response_AbortComplete)(nil),
		(*Response_Failure)(nil),
		(*Response_DirectRestoreReady)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_pagebroker_proto_rawDesc), len(file_v1_pagebroker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_pagebroker_proto_goTypes,
		DependencyIndexes: file_v1_pagebroker_proto_depIdxs,
		EnumInfos:         file_v1_pagebroker_proto_enumTypes,
		MessageInfos:      file_v1_pagebroker_proto_msgTypes,
	}.Build()
	File_v1_pagebroker_proto = out.File
	file_v1_pagebroker_proto_goTypes = nil
	file_v1_pagebroker_proto_depIdxs = nil
}
