# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-License-Identifier: Apache-2.0
[package]
name = "cuinterpose-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
name = "cuinterpose_core"
crate-type = ["cdylib"]

[dependencies]
cuinterpose-abi.workspace = true
cuinterpose-protocol.workspace = true
libc.workspace = true
getrandom.workspace = true
rustix.workspace = true
thiserror.workspace = true
cudarc.workspace = true
